services:
  api:
    build: ./bloodshare-api
    container_name: bloodshare_api
    ports:
      - "3000:3000"
    env_file:
      - ./bloodshare-api/.env
    volumes:
      - ./bloodshare-api:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    command: npm run dev

  db:
    image: postgres:15-alpine
    container_name: bloodshare_db
    environment:
      - POSTGRES_USER=bloodshare
      - POSTGRES_PASSWORD=bloodshare123
      - POSTGRES_DB=bloodshare
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /home/camelia/dev/bloodshare/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bloodshare"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
